version: '3.8'

services:
  sqlserver:
    container_name: ondas_sqlserver
    restart: unless-stopped
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Password123"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - ondas_network

  ondasapi:
    container_name: ondas_api
    restart: unless-stopped
    image: ondasapi:latest
    build:
      context: .
      dockerfile: OndasAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ConnectionStrings__DefaultConnection=Data Source=sqlserver,1433;Initial Catalog=OndasDB;User ID=sa;Password=YourStrong@Password123;TrustServerCertificate=True;MultipleActiveResultSets=true;
      - SUPERADM_EMAIL=superadm@ondas.com
      - SUPERADM_PASSWORD=Ondas@2025
      - JWT__SecretKey=ASIOU3nrsdojf0ej940u98h98-WEF8#peidei4QWy-&*y#equHAHAsJH0Q9JHEQID
      - JWT__ValidAudience=ondas-client
      - JWT__ValidIssuer=ondas-server
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - ondas_network
    depends_on:
      - sqlserver

volumes:
  sqlserver_data:

networks:
  ondas_network:
    driver: bridge